@startwbs 05-documentation
* KEEP Documentation
** Overview
*** Quickstart
*** Use cases
**** Web & Mobile
**** Integration
*** Tutorial
**** Exercising the API
**** Detailed tutorials
** Installation & Configuration
*** Installation
**** Windows (Client & Server)
**** Mac (Client)
**** Linux (Server)
**** Docker (Server)
*** Configuration
**** Port configuration
**** Security configuration
***** HTTPS
***** Authentication & JWT
***** CORS
***** Proxy configuration
*** KEEP Metrics
*** Troubleshooting
** Using KEEP
*** Enabling a database
**** Enabling forms
**** Enabling views
*** KEEP applications
*** The administation UI
**** Database
**** Applications
**** Users & Groups
*** KEEP management API
** How KEEP works
*** OpenAPI
*** The HTTP Handler
*** The Eventbus
*** The Barbican
*** Scopes
*** Architectural Decisions
*** DominoJNX
** Extending KEEP
*** Development Environment
*** OpenAPI
*** Rest principles
*** Web Handlers
*** NSF Handlers
*** Testing
*** JavaDoc
** References
*** Glossary
*** Standards
*** User Tools
**** Installing Eclipse
**** Installing Notes 12
*** Downloads
*** Maven reports
@endwbs