@startuml DBRequestFlow2
start
card subscribe {
    : hasUserRequiredScopes;
    : getActualDatabaseName;
}
card  continueWithActualDbFileName {
    : preflight;
    note: async execution without DominoClient
}
card continueAfterCompletedPreflight {
    : Metrics-Timer;
    : DominoThreadContext;
    : KeeepJnxSession;
}
card executeDominoOperation {
    : secondaryDB;
    note: Used in PIM for Calendars
    : DbRequestParameters;
    : process;
    note: This where the\nactual processing happens\nwith the DbRequestParameters
}
end
@enduml