# Site settings
# Github switched to an Action for Gihub pages that turns the warning into an error
# theme: just-the-docs
remote_theme: Stwissel/just-the-docs
title: "HCL Project KEEP"
description: A modern take on REST interaction with Domino
version: 1.5.1 Beta EA
logo: "/assets/images/svg/HCL_Domino_KEEP_light.svg"
flexnet_url: "https://hclsoftware.flexnetoperations.com/flexnet/operationsportal/entitledDownloadFile.action?downloadPkgId=HCL+Domino+REST+API+Early+Access+Release"
baseurl: "/pages/HCL-Janus/domino-keep-plus-docs/" # the subpath of your site, e.g. /blog
git_url: "https://opensource.hcltechsw.com/domino-keep-docs" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/domino-keep-docs" # the subpath of your site, e.g. /blog
#git_url: "https://opensource.hcltechsw.com" # the base hostname & protocol for your site, e.g. http://example.com
exclude:
  [
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
  ]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 5
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 10
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_insensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

next_page: true

footer_content: "HCL Project KEEP"

# Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/hcl-tech-software/domino-keep-docs" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true
# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false
#   # ignore:
#   #   envs: all
